# Generated by Django 5.1.6 on 2026-03-26 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.CharField(help_text='e.g., sensor_01', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('location_name', models.CharField(blank=True, help_text='e.g., Near basketball Court', max_length=255)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('token', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=10)),
                ('radius', models.FloatField(default=100.0)),
                ('height', models.FloatField(default=1.0)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleFloodThreshold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(help_text='Type of vehicle (e.g., Car, Motorcycle)', max_length=100)),
                ('safe_min', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('safe_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('warning_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('warning_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('danger_min', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('water_level', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='api.sensor')),
            ],
        ),
    ]
