# Generated by Django 5.1.6 on 2026-03-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_emergencycontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='height',
            field=models.FloatField(default=1.0),
        ),
    ]
